# Generated by Django 3.1.7 on 2021-06-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.TextField()),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('attendees', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.TextField()),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('attendees', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Smart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.TextField()),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('attendees', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Truecomp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.TextField()),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('attendees', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
